// text-en.js — English texts (I18N.md). Loaded right after text.js; only used when LANG === 'en'.
// Overwrites, by the same keys, the words in model.js (BODIES, DRUGS, VACCINES, PATHOGENS) and text.js (CELLS, TEAMS, EVENTS, MODE_EVENTS).
// When a Japanese text there is added or changed, change it here too (an entry missing here stays Japanese on the English screen).
'use strict';

if (LANG === 'en') {
  const put = (obj, en) => { for (const [k, v] of Object.entries(en)) if (obj[k]) Object.assign(obj[k], v); };

  put(BODIES, {
    adult: { name:'Healthy adult', note:'A typical example.' },
    child: { name:'Child', note:'Little immune memory yet. Fevers run high easily.' },
    elder: { name:'Older adult', note:'Fewer new T and B cells, so adaptive immunity is slow and weak. The fever may not rise much (it can be serious without anyone noticing).' },
    weak:  { name:'Weak immunity', note:'Example: during cancer treatment, with very few neutrophils.' },
  });

  put(DRUGS, {
    ose:  { name:'Oseltamivir', how:'Pills, twice a day for 5 days',
            text:'A neuraminidase inhibitor. It blocks the “scissors” (neuraminidase) a virus uses to cut itself free from the cell. New viruses stay stuck to the cell surface and cannot get out. It does not remove viruses already released or infected cells. Started within 48 hours of symptoms, it shortens the fever by about a day.' },
    balo: { name:'Baloxavir', how:'Pills, just once',
            text:'It blocks an enzyme (cap-dependent endonuclease) the virus needs to copy its genes in the cell nucleus. Infected cells can no longer make viruses, so the number of viruses falls quickly. It stays in the body a long time, so one dose is enough.' },
    nirm: { name:'Nirmatrelvir (+ ritonavir)', how:'Pills, twice a day for 5 days (for people at risk of getting very sick)',
            text:'It blocks the “scissors” (3CL protease) the COVID-19 virus uses to cut its parts apart. The parts cannot be made, so hardly any new viruses are produced. Ritonavir is taken together to keep the drug from being broken down too fast. Start within 5 days of symptoms. In people at high risk (such as older adults), it greatly reduced hospital stays and severe illness.' },
    ceph: { name:'Cephalexin', how:'Pills, 4 times a day for 7 days',
            text:'An antibiotic in the penicillin family (beta-lactams). When bacteria divide, they cannot build their cell wall (peptidoglycan), so the wall bursts and they die. Human cells have no wall, so it does not affect them. MRSA has a different wall-building enzyme, so it does not work on MRSA. It has trouble reaching bacteria inside pus or inside cells.' },
    vanc: { name:'Vancomycin', how:'IV drip, twice a day for 7 days',
            text:'An antibiotic that sticks to the building blocks of the cell wall in a different way, so the wall cannot be built. It works on MRSA too. But it acts more slowly than beta-lactams, and for ordinary staph, drugs like cephalexin work better.' },
    amox: { name:'Amoxicillin', how:'Pills, 3 times a day for 5–7 days',
            text:'An antibiotic in the penicillin family (beta-lactams). It works well on most pneumococci, breaking the bacteria by stopping them from building their cell wall. In serious cases, patients are hospitalized and given antibiotics by IV.' },
    water:{ name:'Drink plenty of water', how:'Drink more than usual, and do not hold in your pee',
            text:'Peeing more often flushes out the bacteria floating in the urine each time. But bacteria stuck to bladder cells, or hiding inside cells, are not washed away. If there are only a few bacteria, this alone can sometimes cure it.' },
    ors:  { name:'Oral rehydration solution', how:'Drink a little at a time, many times',
            text:'A drink with water, salts (sodium, potassium) and glucose in the right balance to be absorbed easily by the gut, replacing what is lost through diarrhea and vomiting. There is no medicine for norovirus, so preventing dehydration is the most important care. The number of viruses does not change. Anti-diarrhea medicine keeps the virus from being flushed out, so it is usually not used.' },
    apy:  { name:'Fever reducer (acetaminophen)', how:'One dose works for 4–6 hours',
            text:'It acts on the brain’s temperature center and lowers the target temperature. Tiredness and pain also ease. It does not reduce viruses or bacteria, so the course of the illness hardly changes (the number graph stays the same).' },
  });

  put(VACCINES, {
    flu:    { name:'Flu vaccine', kind:'Inactivated vaccine (proteins from broken-up viruses)',
              text:'Proteins such as the spikes (hemagglutinin) taken from broken-up viruses. They cannot multiply, so they cannot make you sick. The types that spread change every year, so the vaccine is remade each year for that year’s types.' },
    covid:  { name:'COVID-19 vaccine', kind:'mRNA vaccine (the blueprint for the spike)',
              text:'The blueprint (mRNA) for the spike protein, wrapped in tiny fat droplets. Cells such as arm muscle read the blueprint and make only the spike, which the immune system learns. The mRNA breaks down in a few days and does not enter the genes in the nucleus. Fever and tiredness are more common after the second dose.' },
    pneumo: { name:'Pneumococcal vaccine', kind:'Conjugate vaccine (capsule sugar + protein)',
              text:'The sugar of the bacterial capsule, linked to a protein the immune system reacts to strongly. Antibodies to the capsule are made, so the bacteria are easier to eat. There are over 90 capsule types, and it works only on the types in the vaccine.' },
  });

  put(PATHOGENS, {
    flu:    { name:'Influenza virus', short:'Flu', site:'Lining of the nose and throat', route:'Breathing in droplets from coughs and sneezes, which land on the lining of the nose and throat.',
              memOptions:{ none:'None', vac:'Got the vaccine', prior:'Had the same type before' } },
    covid:  { name:'COVID-19 virus', short:'COVID', site:'Lining of the nose and throat (sometimes lungs)', route:'Breathing in droplets from coughs, sneezes and talking, or tiny particles floating in the air (aerosols).',
              memOptions:{ none:'None', vac:'Got the vaccine', prior:'Had it before' } },
    noro:   { name:'Norovirus', short:'Noro', site:'Lining of the small intestine', route:'Gets into the mouth from hands or food with the virus on it (such as undercooked shellfish), or droplets of vomit or stool.',
              memOptions:{ none:'None', prior:'Had it before (fades in months to years)' } },
    staph:  { name:'Staphylococcus aureus', short:'Staph', site:'A wound in the skin', route:'Bacteria that normally live on the skin or in the nose get in through a scrape or cut.',
              memOptions:{ none:'None', prior:'Had it before (a few antibodies)' }, resistName:'MRSA (hard-to-treat staph)' },
    pneumo: { name:'Pneumococcus', short:'Pneumococcus', site:'Deep in the lungs (alveoli)', route:'Bacteria living in the nose and throat get breathed deep into the lungs when the body is weakened, for example by a cold.',
              memOptions:{ none:'None', vac:'Got the pneumococcal vaccine', prior:'Had it before (same type)' } },
    ecoli:  { name:'E. coli (bladder infection)', short:'E. coli', site:'Inside the bladder', route:'Gut bacteria from around the bottom travel up the urethra from the urine opening into the bladder (more common in women, whose urethra is short).',
              memOptions:{ none:'None', prior:'Had it before (often comes back)' } },
  });

  put(CELLS, {
    virion: { name:'Influenza virus', size:'About 0.1 µm across (shown about 20× larger)',
      text:'On its fatty membrane are about 300 spikes (hemagglutinin: rods with round tips) and about 50 mushroom-shaped spikes (neuraminidase). Inside are genes (RNA) split into 8 pieces. Some are long and thin. It cannot move on its own; it is only carried by the flow and jiggling (diffusion) of mucus. It does not multiply outside cells. It sticks to sugars (sialic acid) on the cell surface, gets swallowed and multiplies inside the cell (① to ⑤ on screen). Neuraminidase is used to cut through mucus to reach cells, and to cut new viruses free from the cell.' },
    cell: { name:'Ciliated epithelial cell', size:'About 20–30 µm tall',
      text:'Cells lining the inside of the nose and throat. Each has about 200 cilia on top that beat quickly toward the throat more than 10 times a second, carrying the mucus. These are the cells the flu virus gets into and multiplies in.' },
    goblet: { name:'Goblet cell', size:'About 20–30 µm tall',
      text:'A cell that stores and releases the raw material of mucus (mucin). About one in every few lining cells is one. Viruses can get into these cells too.' },
    infected: { name:'Hijacked cell (infected cell)',
      text:'Once the virus genes reach the nucleus, the cell’s materials and machinery are used to make viruses. For the first few hours nothing shows from outside (the eclipse phase). After about 6 to 8 hours, parts gather at the surface and new viruses bud out — thousands from one cell. The cilia are lost, and the cell eventually dies. It started as one of our own cells, but because it has become a virus factory, NK cells and killer T cells destroy it.' },
    protectedCell: { name:'Cell on guard',
      text:'A cell that received “interferon”, the alarm signal released by infected cells (light-blue outline). It prepares substances that destroy virus genes or stop them from being copied, so even if a virus gets in, it multiplies poorly. Interferon also causes fever and tiredness.' },
    mucus: { name:'Mucus and cilia', size:'Mucus about 5–10 µm, watery layer about 7 µm',
      text:'Around the cilia is a thin watery layer, with sticky mucus on top. Viruses, bacteria and dust get caught in the mucus and are carried by the cilia to the throat, swallowed, and broken down by stomach acid. The real speed is a few mm a minute (fast enough to cross this screen in under a second). It is drawn slowly so you can see it. The mucus also holds antibodies (IgA) that flow along with it.' },
    macrophage: { name:'Macrophage', size:'About 20 µm across',
      text:'The “big eater”. It wraps up whole viruses, bacteria and dead cells, eats them, and breaks them down in an inner bag (phagosome). Most live in the tissue under the lining and clean up pieces of dead cells. Some live on the airway surface under the mucus (especially many deep in the lungs, few in the nose).' },
    nk: { name:'NK cell (natural killer cell)', size:'About 12 µm across',
      text:'A large lymphocyte full of granules, a born “killer”. Infected cells lose some of their surface ID tags (MHC) or show stress signs. The NK cell finds them and pours in a substance that punches holes (perforin) and enzymes that break things down (granzymes), making the cell destroy itself. It does not need to learn in advance, so it can work within days.' },
    ctl: { name:'Killer T cell', size:'About 7–10 µm across',
      text:'A small lymphocyte whose nucleus fills the cell. A specialist “killer” that recognizes pieces of only that one virus. There are only a few hundred at first, but when shown the pieces in a lymph node, they divide every 6 to 8 hours, multiply tens of thousands of times in a few days, and arrive through the blood. They squeeze into the lining, attach to infected cells and destroy them. They start working around day 5 to 7.' },
    helper: { name:'Helper T cell', size:'About 7–10 µm across',
      text:'The immune system’s “command center”. It helps B cells make antibodies and sends signals (such as IL-17) that call neutrophils. It does not destroy enemies itself.' },
    plasma: { name:'Plasma cell', size:'About 10–15 µm across',
      text:'An “antibody factory” that a B cell turns into. It makes thousands of antibodies a second. Plasma cells under the lining mostly make IgA, which the lining cells carry from below to above (transcytosis) and release into the mucus. You can spot them by the clock-face pattern of the nucleus.' },
    antibody: { name:'Antibody', size:'About 0.01 µm long (drawn very large on screen)',
      text:'A Y-shaped protein. The tips of its two arms fit their target exactly. IgA in mucus is two Ys joined together; flowing with the mucus, it sticks to viruses so they cannot enter cells (neutralization). IgG from the blood is a single Y; when it sticks to bacteria, they are easier for neutrophils and macrophages to eat (opsonization). Against a new enemy it takes 1 to 2 weeks, but with memory, large amounts are made in a few days.' },
    dc: { name:'Dendritic cell', size:'About 50 µm with arms stretched out',
      text:'A “messenger” that stretches out long arms to collect pieces of the enemy. In the airway it reaches its arms between the lining cells up to the surface to check outside. With a piece in hand, it travels through lymph vessels to a lymph node and shows the piece to T cells and B cells, switching on adaptive immunity.' },
    rbc: { name:'Red blood cells (capillary)', size:'About 7.5 µm across',
      text:'Capillaries are the route for immune cells and antibodies. When inflammation starts, blood vessels widen and their walls loosen, and neutrophils and others slip through gaps in the wall into the tissue (migration). Fluid from the blood also leaks out, causing red swelling.' },
    bacterium: { name:'Staphylococcus aureus', size:'About 1 µm across (shown about 2× larger)',
      text:'A round bacterium with a thick cell wall (peptidoglycan). It multiplies by splitting in two, in a different direction each time, so it gathers in clusters like bunches of grapes. It normally lives on human skin and in the nose, but when it gets in through a wound it multiplies outside cells (unlike viruses, it can multiply on its own). Its toxins break cells, and it also releases substances that destroy neutrophils. “Aureus” means golden, from the golden color of its colonies.' },
    neutrophil: { name:'Neutrophil', size:'About 12 µm across',
      text:'The most common white blood cell. When bacteria get in, neutrophils come out of the blood vessels within hours, crawl toward the bacteria following signal substances, and eat and kill them. You can spot them by the nucleus pinched into 3 to 5 lobes. They live 1 to 2 days, and neutrophils that died fighting, plus bacteria and tissue pieces, become “pus”.' },
    complement: { name:'Complement', size:'Proteins (very small)',
      text:'A team of proteins always present in blood and tissue fluid. They stick to the bacterial surface one after another and attach a tag (C3b), making the bacteria easier to eat. The “first line of defense” that works right after bacteria get in.' },
    pus: { name:'Pus',
      text:'A collection of neutrophils that died fighting, bacteria and broken tissue. When fibers wall it off into an “abscess”, the bacteria are trapped, but immune cells and antibiotics also have trouble reaching the bacteria inside. A large abscess is cut open and drained.' },
    fibroblast: { name:'Fibroblast (dermis)', size:'About 30–50 µm long',
      text:'A cell in the lower layer of the skin (dermis) that makes collagen fibers. It works when wounds heal. When damaged by bacterial toxins it turns gray.' },
    keratinocyte: { name:'Epidermal cell', size:'About 10–30 µm',
      text:'The outermost layer of skin. It is many layers thick, and its outside is a tough layer of dead cells (stratum corneum) that normally keeps bacteria out. A wound becomes a doorway.' },
    drug: { name:'Medicine molecules', size:'Very small (shown as dots)',
      text:'Medicine you swallow enters the blood from the gut and seeps out of capillaries into tissues and cells. To see where and how it works, read the medicine’s description (in Events).' },
    corona: { name:'COVID-19 virus', size:'About 0.1 µm across (shown about 20× larger)',
      text:'From its fatty membrane stick out “spikes” with swollen tips, like a crown (corona). It uses the spikes to stick to a protein on the cell surface (ACE2) and enters the cell. Its gene is one long RNA. It multiplies more slowly than flu and suppresses the interferon alarm, so it multiplies before symptoms appear and can spread from then. It cannot move on its own; it is only carried by mucus.' },
    noro: { name:'Norovirus', size:'About 0.03 µm across (about 1/3 of flu; drawn large on screen)',
      text:'A small virus with no fatty membrane, made only of a hard protein shell (an icosahedron). That is why it resists stomach acid, drying out and alcohol sanitizer. It multiplies in cells of the small intestine, and hundreds of millions come out per gram of stool or vomit. It is so contagious that just a dozen to a few dozen can infect you. It cannot move on its own.' },
    pneumo: { name:'Pneumococcus', size:'About 1 µm long (shown about 2× larger)',
      text:'Round bacteria with pointed ends, lined up in pairs. A thick, slimy sugar coat called the “capsule” surrounds them, so neutrophils and macrophages have trouble catching them. Only when antibodies stick to the capsule can they be eaten. That is why the vaccine makes antibodies against the capsule. They live in the nose and throat and get deep into the lungs when the body is weakened by a cold or similar.' },
    ecoli: { name:'E. coli (urinary type)', size:'About 2 µm long (shown about 2× larger)',
      text:'A long, rod-shaped bacterium common in the gut. The types that cause bladder infections swim with flagella and stick to bladder surface cells with sticky hairs (pili) at their tips. Once stuck, they are not washed away by urine. They can also enter cells and form clumps (intracellular bacterial communities), which medicines and immune cells have trouble reaching. This is one reason infections come back.' },
    enterocyte: { name:'Absorptive cell (small intestine)', size:'About 20–30 µm tall',
      text:'Cells lining the small intestine. Thousands of tiny “microvilli” stand on their surface (the brush border), absorbing nutrients and water. When infected by norovirus, the microvilli shrink and cannot absorb water, causing diarrhea. They are replaced by new cells every 3 to 5 days.' },
    gutMucus: { name:'Gut mucus',
      text:'Mucus covering the gut lining. It protects the cells from food and gut bacteria. It contains lots of antibodies (IgA).' },
    chyme: { name:'Contents of the small intestine',
      text:'Partly digested food and digestive juices. Gut movements (peristalsis) carry them along, and in the end they become stool. Viruses are carried along too and leave the body in stool.' },
    alvWall: { name:'Alveolar wall', size:'About 0.5 µm thick (wall cells)',
      text:'The wall of the tiny grape-like sacs (alveoli). Right under very thin cells (type I) are capillaries, where oxygen enters the blood. Round cells (type II) here and there make a liquid (surfactant) that keeps the alveoli from collapsing. In pneumonia, fluid and neutrophils seep out of the blood vessels and fill the alveoli, so oxygen has trouble getting in.' },
    airspace: { name:'Inside the alveolus (air)', size:'About 0.2 mm across',
      text:'The inside of the sac where breathed-in air goes. In pneumonia it fills with fluid and cells (it looks white on an X-ray). Watchman cells called alveolar macrophages normally live here.' },
    umbrella: { name:'Umbrella cell (bladder surface)', size:'About 50–100 µm wide',
      text:'Large, flat cells forming the innermost layer of the bladder. Their surface is covered with hard plates (uroplakins) so urine does not soak in. They may have two nuclei. When bacteria stick to them, these cells peel themselves off and leave in the urine along with the bacteria (a defense). The cells below become the new surface.' },
    urine: { name:'Urine',
      text:'Made by the kidneys and stored in the bladder. Normally it has no bacteria. Peeing about 6 times a day flushes out floating bacteria. When bacteria are present, neutrophils also come out into the urine, making it cloudy.' },
  });

  Object.assign(TEAMS, { enemy:['Enemy', TEAMS.enemy[1]], ally:['Ally (immune)', TEAMS.ally[1]], self:['Body cells and tissue', TEAMS.self[1]], drug:['Medicine', TEAMS.drug[1]] });

  const EV_EN = {
    flu: {
      start:['Viruses landed in the nose and throat', 'Viruses carried by droplets from a cough or sneeze landed on the mucus. The mucus traps them, and the cilia try to carry them to the throat and throw them away. Macrophages eat them too.'],
      enter:['A virus got into a cell', 'A virus that slipped through the mucus stuck to sugars (sialic acid) on a cell surface and was swallowed. Inside, it takes off its coat and sends its genes (RNA) into the nucleus. For a while, nothing shows from outside.'],
      burst:['New viruses came out', 'About 6 to 8 hours after getting in, new viruses come out of the infected cell’s surface — thousands from one cell. They go on to enter neighboring cells.'],
      ifn:['The interferon alarm', 'Infected cells released “interferon”. Nearby cells switch into a state where viruses multiply poorly (blue outline). NK cells and macrophages are called in too.'],
      nk:['NK cells gathered', 'NK cells found cells whose surface ID tags changed because of infection and began destroying them. Wrecking the virus factories slows the increase.'],
      fever:['A fever started', 'Substances such as interferon acted on the brain’s temperature center and raised the target temperature. Fever is thought to help immune cells work and make it harder for viruses to multiply. Tiredness, headache and joint pain come from the same substances.'],
      lymph:['Pieces reached the lymph nodes', 'Dendritic cells carried pieces of the virus through lymph vessels to the lymph nodes. There, killer T cells and B cells that match this virus are chosen and start dividing. That is why the lymph nodes in your neck swell.'],
      peak:['The virus count has passed its peak', 'The number of viruses has passed its highest point, because fewer cells can be infected (cells on guard, dead cells) and because of innate immunity.'],
      ctl:['Killer T cells arrived', 'Killer T cells that multiplied tens of thousands of times in the lymph nodes reached the infected area. They target and destroy only cells infected with this virus. From here, the virus count drops quickly.'],
      lung:['It may spread to the bronchi and lungs', 'Much of the lining is damaged. If the virus spreads to the lower airways, or bacteria settle on the damaged lining, pneumonia can develop. This is more likely in older adults and people with weak immunity.'],
      ab:['Antibodies are increasing', 'Plasma cells, changed from B cells, began making large amounts of antibodies. Viruses with antibodies stuck to them cannot enter cells (neutralization). They will also work right away the next time the same virus comes.'],
      cool:['The fever went down', 'Viruses and infected cells decreased, interferon and the like decreased too, and body temperature returned to normal.'],
      blocked:['No infection', 'Only a few viruses got in, and mucus, cilia and macrophages alone cleared them. They were thrown out before multiplying inside cells, so there is no fever and no symptoms.'],
      clear:['The viruses are gone', 'Both the viruses and the infected cells are gone. The damaged lining heals over 1 to 2 weeks (a cough may linger). Some killer T cells and B cells remain for years as “memory cells” and multiply quickly if the same virus comes again.'],
    },
    staph: {
      start:['Bacteria got in through a wound', 'The tough outer layer of skin (stratum corneum) was cut, and Staphylococcus aureus living on the skin got in. Right away, complement tags the bacteria and resident macrophages begin eating them.'],
      neut:['Neutrophils came out of the blood vessels', 'Signals released by macrophages (such as IL-8) loosened the blood vessel walls, and within hours neutrophils slipped through one after another. Fluid from the blood also leaks out, causing red swelling.'],
      grow:['The bacteria are multiplying and spreading', 'The bacteria are multiplying faster than the neutrophils can eat them. Their toxins damage cells, and the infection spreads under the skin (cellulitis).'],
      pus:['Pus has collected', 'Neutrophils that died fighting, plus bacteria and tissue pieces, became “pus”. Fibers surround it, trying to trap the bacteria (an abscess).'],
      fever:['A fever started', 'Inflammatory substances (IL-1, IL-6, TNF and others) traveled in the blood to the brain and raised the target temperature.'],
      lymph:['Pieces reached the lymph nodes', 'Pieces of the bacteria traveled through lymph vessels to the lymph nodes in the armpit. There, T cells and B cells that match the bacteria start to multiply.'],
      blood:['Bacteria entered the blood', 'Bacteria got into the blood from the damaged tissue (bacteremia). Usually macrophages in the spleen and liver clear them quickly, but if they cannot keep up, inflammation spreads through the whole body (sepsis). This needs antibiotic treatment at a hospital right away.'],
      th:['Helper T cells joined in', 'The increased helper T cells send signals that call more neutrophils and help B cells make antibodies.'],
      ab:['Antibodies began tagging the bacteria', 'When antibodies stick to bacteria, neutrophils and macrophages catch them more easily (opsonization). But Staphylococcus aureus also has tricks to dodge antibodies, so people can get it again and again.'],
      cool:['The fever went down', 'The bacteria and inflammatory substances decreased, and body temperature came back down.'],
      blocked:['Cleared right away', 'Only a few bacteria got in, and complement and the resident macrophages alone cleared them. It barely turns red. This is normal for small wounds.'],
      clear:['The bacteria are gone', 'The bacteria are gone. Macrophages clean up the remaining pus, or it drains out through the skin. Fibroblasts make fibers to repair the damaged area (a big one may leave a scar).'],
    },
    covid: {
      start:['Viruses landed in the nose and throat', 'Viruses carried by droplets or tiny particles floating in the air (aerosols) landed on the mucus. The mucus and cilia try to carry them to the throat.'],
      enter:['A virus got into a cell', 'Using its spikes, the virus stuck to a protein on the cell surface (ACE2), merged with the cell membrane and got in. Its genes (RNA) start being read right away as blueprints for parts.'],
      burst:['New viruses came out', 'New viruses were assembled inside membrane bags made in the cell and sent out. It is slower than flu, taking half a day to a day.'],
      quiet:['Multiplying before symptoms appear', 'This virus gets in the way of infected cells sending out the alarm (interferon). So the body notices late, and viruses build up before symptoms appear. From this point it spreads easily to other people.'],
      ifn:['The interferon alarm (late)', 'At last the alarm spreads, and nearby cells begin to guard themselves. NK cells gather too.'],
      fever:['A fever started', 'Signal substances such as interferon reached the brain’s temperature center and raised the target temperature.'],
      smell:['Smell may become hard to sense', 'When the virus damages the cells that support the smell nerves deep in the nose (support cells), smell and taste can become hard to sense. They usually come back in a few weeks.'],
      ctl:['Killer T cells arrived', 'Killer T cells that multiplied in the lymph nodes began destroying infected cells.'],
      lung:['It may spread to the lungs (pneumonia)', 'Much of the lining is damaged. If the virus spreads deep into the lungs, pneumonia can develop and breathing can become hard. This is more likely in older adults and people with weak immunity.'],
      ab:['Antibodies are increasing', 'Antibodies stick to the spikes, so the virus can no longer enter cells.'],
      cool:['The fever went down', 'Viruses and infected cells decreased, and the fever settled.'],
      blocked:['No infection', 'Only a few viruses got in, and mucus and macrophages alone cleared them.'],
      clear:['The viruses are gone', 'The viruses are gone. Cough and tiredness can last for weeks. Memory cells remain, but when the virus changes (variants), antibodies stick less well.'],
    },
    noro: {
      start:['Viruses got in through the mouth', 'They got into the mouth from hands or food with the virus on them. The shell is hard and resists stomach acid, so they reach the small intestine intact.'],
      enter:['A virus got into a cell of the small intestine', 'It latched onto a cell of the intestinal lining and got in. Infection starts with very few viruses — even a few dozen can infect.'],
      burst:['Viruses multiplied and came out', 'Huge numbers of new viruses come out of infected cells and spread to neighboring cells. They are carried along with the gut contents and come out in stool.'],
      vomit:['Nausea and vomiting started', 'Sudden nausea and vomiting often come 1 to 2 days after infection. Vomit also contains lots of virus, which spreads to the next person through splashes and dried residue. Clean up with gloves and a mask, using a chlorine-based disinfectant.'],
      diarrhea:['Diarrhea started', 'Infected cells died or their microvilli shrank, so the gut can no longer absorb water. Water is also pushed into the gut, causing diarrhea.'],
      dehyd:['Risk of dehydration', 'A lot of water and salt is being lost. Children and older adults especially should drink oral rehydration solution or similar a little at a time. If they cannot pee or seem limp, go to a hospital.'],
      ifn:['The interferon alarm', 'Alarms from infected cells made nearby cells guard themselves. In the gut this alarm is especially important.'],
      ab:['Antibodies (IgA) are increasing', 'Antibodies released into the gut mucus (IgA) stick to the virus so it cannot enter cells. But they weaken in months to years, so people can catch it again.'],
      clear:['The viruses are gone', 'Symptoms usually settle in 1 to 3 days. In reality, the virus can keep coming out in stool for 1 week to 1 month after recovery, so keep washing hands (in the model it reaches 0 sooner).'],
    },
    pneumo: {
      start:['Bacteria got deep into the lungs', 'Pneumococci living in the nose and throat were breathed into the tiny sacs deep in the lungs (alveoli). Alveolar macrophages keep watch, but the capsule makes the bacteria hard to catch.'],
      neut:['Neutrophils came out of the blood vessels', 'Answering the signals, neutrophils came out of the capillaries into the alveoli. Fluid from the blood seeps out too.'],
      grow:['Bacteria are multiplying and filling the alveoli', 'There are no antibodies yet, so the capsule-covered bacteria cannot all be eaten. Fluid and neutrophils fill the alveoli, and air cannot get in (it looks white on an X-ray).'],
      fever:['A fever started', 'Inflammatory substances reached the brain, and a high fever comes with chills.'],
      breath:['The blood is running short of oxygen', 'In filled alveoli, oxygen cannot get into the blood. Breathing becomes hard and fast. In a hospital, patients get oxygen to breathe.'],
      blood:['Bacteria entered the blood', 'Bacteria got into the blood from the lungs (bacteremia). This easily becomes serious, so antibiotic treatment is needed right away.'],
      ab:['Antibodies caught hold of the capsule', 'Antibodies made by B cells stuck to the capsule, and neutrophils and macrophages could now eat the bacteria. Before antibiotics, the sudden drop in fever around day 7 (the “crisis”) happened at this moment.'],
      cool:['The fever went down', 'The bacteria decreased and the fever settled. It takes several more weeks for the filled alveoli to recover.'],
      blocked:['Cleared right away', 'Only a few bacteria got in, and alveolar macrophages and complement alone cleared them.'],
      clear:['The bacteria are gone', 'The bacteria are gone. Macrophages clean up the leftover fluid and cells, and air returns to the alveoli.'],
    },
    ecoli: {
      start:['Bacteria entered the bladder', 'E. coli from around the bottom traveled up the urethra from the urine opening into the bladder. Bacteria floating in the urine are flushed out each time you pee.'],
      stick:['Bacteria stuck to bladder cells', 'With the tips of their hairs (pili), the bacteria stuck to the umbrella cells on the bladder surface. Now urine cannot wash them away. They also get inside cells and multiply.'],
      alarm:['Bladder cells sent an alarm', 'Cells that noticed the bacteria released signal substances and called neutrophils. Umbrella cells with bacteria on them peel themselves off to wash the bacteria away.'],
      pain:['Peeing started to hurt', 'The bladder lining is inflamed, and peeing stings. You need the toilet even when only a little has collected.'],
      pyuria:['The urine is getting cloudy', 'Many neutrophils came out into the urine, making it cloudy (a test finds white blood cells).'],
      kidney:['It may spread to the kidneys', 'If bacteria travel up the ureters to the kidneys, high fever and back (side) pain appear (kidney infection, pyelonephritis). Go to a hospital right away.'],
      ab:['Antibodies are increasing', 'Antibodies stick to the bacteria’s pili and make it harder for them to stick to cells.'],
      clear:['Symptoms settled', 'Hardly any bacteria remain in the urine, and the inflammation has settled. But a few bacteria hidden deep in cells may remain, and if they multiply later, the infection comes back.'],
    },
  };
  for (const [pk, list] of Object.entries(EVENTS)) for (const e of list) { const t = EV_EN[pk] && EV_EN[pk][e.id]; if (t) { e.title = t[0]; e.text = t[1]; } }

  const MODE_EN = {
    vaccine: {
      vacDC:['Vaccine pieces went to the lymph nodes', 'At the injection site, dendritic cells took in pieces of the vaccine and carried them to a nearby lymph node. Unlike the real germ, they do not multiply, so you do not get sick.'],
      vacB:['Matching B cells and T cells began to multiply', 'Out of millions of kinds of B cells and T cells, only the ones that fit this piece exactly are chosen and multiply. In the lymph node’s “germinal centers”, B cells are slowly reshaped to make antibodies that stick more firmly.'],
      vacAb:['Antibodies are forming', 'About 2 weeks after the first shot, antibodies increased in the blood. The body has not met the real thing yet.'],
      vacBoost:['A big jump after the second shot', 'Memory B cells made by the first shot reacted to the second shot’s pieces right away and multiplied. Antibodies become many times more than after the first shot and last longer (booster effect).'],
      vacMem:['Ready', 'Antibodies and memory cells are in place. Try the “gets in” button in the panel to see what happens if the real thing comes now.'],
    },
    second: {
      memT:['Memory T cells multiplied right away', 'The first time, killer T cells (and helper T cells) took 5 to 7 days to start working. The second time, there are hundreds of times more memory cells left, and they react to even a few pieces, so they multiplied in 2 to 3 days.'],
      memAb:['Memory B cells quickly made lots of antibodies', 'Memory B cells quickly turn into plasma cells and make many more antibodies, much sooner than the first time. The germs are often cleared before they can multiply.'],
    },
  };
  for (const [m, list] of Object.entries(MODE_EVENTS)) for (const e of list) { const t = MODE_EN[m] && MODE_EN[m][e.id]; if (t) { e.title = t[0]; e.text = t[1]; } }
}
