'use strict';
// text-en.js — English texts for the record (data.js) and the species names (life.js). I18N.md.
// Loaded right after data.js. Only used when LANG==='en': GEO, KIND, EVENTS and ANCESTORS are overwritten
// in place (same order as data.js), SP_EN is read by S() in life.js. When a text in data.js changes, change it here too.

const GEO_EN=['Hadean','Archean','Proterozoic','Phanerozoic','Paleoproterozoic','Mesoproterozoic','Neoproterozoic','Paleozoic','Mesozoic','Cenozoic',
 'Tonian','Cryogenian','Ediacaran','Cambrian','Ordovician','Silurian','Devonian','Carboniferous','Permian','Triassic','Jurassic','Cretaceous',
 'Paleogene','Neogene','Quaternary','Pleistocene','Holocene'];

const EVENTS_EN=[
['Molecular cloud collapses','A cloud of gas and dust in the galaxy (a molecular cloud) starts to shrink under its own weight. One idea is that a nearby supernova set it off.'],
['The Sun and the protoplanetary disk','The young Sun forms at the center, with a disk of gas and dust circling it. The dust sticks together and grows into planetesimals a few km across. The oldest solids in the Solar System date to this time.'],
['Earth is born','Planetesimals crash and merge into the young Earth. The heat of the impacts melts the surface, covering it with a sea of magma (magma ocean) hundreds of km deep.'],
['Giant impact and the birth of the Moon','A Mars-sized body called Theia is thought to have hit Earth, and the scattered pieces gathered into the Moon (the date is debated). The new Moon was much closer, and a day lasted only about 5 to 6 hours.'],
['Oceans form','The surface cooled and hardened, and water vapor in the air fell as rain for a long time, making the oceans. Mineral grains (zircons) about 4.4 billion years old show there was already liquid water. The Sun was about 30% dimmer than today.'],
['Late Heavy Bombardment','About 4.1 to 3.8 billion years ago, many small bodies are thought to have rained down on Earth and the Moon. Many of the Moon’s craters date from this time (whether the impacts really clustered then is debated).'],
['The Archean begins','The age of Earth’s oldest surviving rocks, such as the Acasta Gneiss in Canada (about 4 billion years old).'],
['Traces of life','Rocks in Greenland hold carbon that may have been made by living things. Whether life began at deep-sea hydrothermal vents or in hot-spring-like pools on land is still unknown.'],
['Stromatolites','Rocks built up from layers of microbial mats. They remain in layers about 3.5 billion years old in Western Australia. Shallow sea floors were covered with films of microbes.'],
['Oxygen-making photosynthesis','Cyanobacteria began photosynthesis that splits water and gives off oxygen (some say even earlier). For a while the oxygen reacted with iron dissolved in the sea and disappeared.'],
['The Proterozoic begins','Large continents grow and shallow seas spread.'],
['Great Oxidation Event','Oxygen began to build up in the air. Iron in the sea rusted and sank, forming banded iron formations. Methane, a greenhouse gas, decreased, and the sky, thought to have been orange from a methane haze, turned blue.'],
['Huronian glaciation','With less methane the greenhouse effect weakened, and a worldwide ice age began (about 2.4 to 2.1 billion years ago).'],
['Eukaryotes appear','Eukaryotes, large cells with a nucleus and mitochondria, appeared (the timing is debated). Mitochondria are descendants of bacteria taken into the cell.'],
['Multicellular algae','Red and green algae came to have bodies made of many cells.'],
['Snowball Earth','Twice the whole Earth froze, with ice reaching the equator (about 720 to 635 million years ago). The sea was shut under a thick lid of ice.'],
['End of the Snowball','The greenhouse effect of carbon dioxide that volcanoes kept giving off melted the ice, and the climate warmed quickly.'],
['Ediacaran biota','Large, soft-bodied creatures appeared on the sea floor, like leaf-shaped Charnia and flat oval Dickinsonia.'],
['Cambrian explosion','The Paleozoic begins. Animals with eyes, hard shells and legs appeared one after another in a short time: trilobites, the big predator Anomalocaris, and small fish-like animals with a notochord, the forerunner of the backbone.'],
['Plants move onto land','Moss-like plants began to spread over the land. Until then the land was bare rock and sand.'],
['End-Ordovician mass extinction','Africa then lay near the South Pole, and a large ice sheet formed. Sea level fell, and about 85% of sea species disappeared. Traces of these glaciers remain in the Sahara today.'],
['Vascular plants','Plants with tubes that carry water, like Cooksonia, appeared. They were a few cm tall. In the sea, jawed fish increased and sea scorpions thrived.'],
['The first forests','Trees over 10 m tall, such as Archaeopteris, formed forests. The Devonian is also called the “Age of Fishes”.'],
['Tiktaalik','A fish with arm-like bones in its fins and a neck it could move. It lived in shallow water at the edge, showing a step on the way to four-legged animals on land.'],
['Late Devonian mass extinction','With less oxygen in the sea and other changes, many coral reefs and armored fish disappeared.'],
['Carboniferous forests','Swamp forests of giant fern-like plants such as Lepidodendron spread, and their remains became today’s coal. Oxygen in the air rose above 30%, and dragonflies (Meganeura) with 70 cm wingspans flew.'],
['The shelled egg','Amniotes appeared and could lay eggs on dry land. Soon they split into synapsids (the line leading to mammals) and the line of reptiles and birds.'],
['The Permian and Pangaea','The continents came together into the supercontinent Pangaea, and the interior dried out. Synapsids such as sail-backed Dimetrodon became the main land animals.'],
['The largest mass extinction ever','Huge volcanic eruptions in Siberia drove warming and oxygen loss in the sea, and over 80% of sea species disappeared. The survivor Lystrosaurus for a time made up most land animals.'],
['Dinosaurs appear','In the late Triassic, small dinosaurs that ran on two legs appeared.'],
['The first mammal relatives','Mouse-sized mammaliaforms appeared. Through the age of dinosaurs most stayed small and were active at night.'],
['End-Triassic mass extinction','Pangaea began to split, and great eruptions broke out along the rift that later became the Atlantic. With fewer rivals, dinosaurs grew large and thrived in the Jurassic.'],
['Juramaia','One of the oldest mammals linked to placental mammals, including humans. About 10 cm long, it climbed trees and ate insects.'],
['Birds appear','Some feathered dinosaurs, like Archaeopteryx, began to fly. Birds are surviving dinosaurs.'],
['Flowering plants','Angiosperms appeared and spread through the Cretaceous.'],
['Asteroid impact and the end of the dinosaurs','An asteroid about 10 km across hit Mexico’s Yucatán Peninsula. Dust thrown up blocked the sunlight, and about 75% of species disappeared, including non-bird dinosaurs, pterosaurs, plesiosaurs and ammonites.'],
['The age of mammals','The small mammals that survived spread quickly into the empty places. Ferns were the first to sprout on the burned ground.'],
['Paleocene–Eocene Thermal Maximum','A large amount of carbon entered the air in a short time, and temperatures rose by 5 to 8 ℃. Forests spread to the poles, and early primates appeared in many places.'],
['Ice sheet on Antarctica','Carbon dioxide fell and the climate cooled, and a large ice sheet formed on Antarctica.'],
['The age of apes','Tailless apes such as Proconsul, found on the shore of Lake Victoria in Kenya, thrived in the forests of Africa.'],
['The Rift Valley and spreading grasslands','The land of East Africa rose and split, and the Great Rift Valley began to form. The highlands blocked the rain, the land dried, and forests slowly turned into grasslands.'],
['Humans appear','The lines of humans and chimpanzees split. Sahelanthropus, found in Chad (about 7 million years ago), may have stood on two legs.'],
['Ardipithecus','“Ardi” from Ethiopia. It lived in forests but walked on two legs on the ground. Its big toe could still grasp things.'],
['Laetoli footprints','In volcanic ash in Tanzania, footprints remain where Australopithecus walked on two legs.'],
['The oldest stone tools','Stone tools about 3.3 million years old have been found on the west shore of Lake Turkana in Kenya (Lomekwi).'],
['Lucy','A skeleton of Australopithecus afarensis found in Ethiopia. About 1.1 m tall.'],
['The genus Homo appears','A jawbone about 2.8 million years old found in Ethiopia is thought to be the oldest member of the genus Homo.'],
['The Quaternary ice age','Ice sheets spread in the Northern Hemisphere, and glacial and interglacial periods began to repeat. In Africa, wet and dry times took turns, and lakes grew and shrank.'],
['Homo erectus','With long legs it walked long distances and was the first to spread beyond Africa. On the shore of Lake Turkana, a boy’s skeleton about 1.5 million years old (Turkana Boy) has been found.'],
['Hand axes','Teardrop-shaped stone tools chipped on both sides (Acheulean culture). The oldest, about 1.76 million years old, were found in Kenya.'],
['Using fire','Wonderwerk Cave in South Africa holds traces of fire used about 1 million years ago. Fire was used to cook and for protection from the night cold and from animals.'],
['Homo sapiens','Our species. Fossils about 300,000 years old found at Jebel Irhoud in Morocco are among the oldest.'],
['Out of Africa','About 70,000 to 60,000 years ago, some Homo sapiens left Africa and spread around the world.'],
['The Holocene and farming','The last ice age ended. Farming began in West Asia and elsewhere. At this time the Sahara was a “Green Sahara” of grasslands and lakes.'],
['Herding reaches East Africa','Herders with cattle and goats spread around Lake Turkana. Around the same time, writing and cities began in Egypt and Mesopotamia.'],
['Iron and farming spread','People with iron tools and farming spread through East Africa, and villages and fields grew.'],
['Industrial Revolution','Steam engines began burning coal, and carbon dioxide emissions began to rise quickly.'],
['Uganda Railway','A railway opened from Mombasa on the Indian Ocean to Lake Victoria (1901). The town of Nairobi grew up as a base for this railway.'],
['The Great Acceleration','From around 1950, population, energy use, carbon dioxide and more shot up.'],
['Today','The world population is about 8.2 billion. Carbon dioxide is about 425 ppm, about 50% more than before the Industrial Revolution.'],
];

const ANCESTORS_EN=[
['Not yet','Life has not begun yet.'],
['The first life (debated)','When and where life began is unknown. Some studies put the last universal common ancestor (LUCA) of all living things at about 4.2 billion years ago.'],
['Prokaryotes','Tiny cells with no nucleus. Too small to see, they lived in microbial mats in shallow seas.'],
['Eukaryotes (single-celled)','Cells with a nucleus and mitochondria. They still live as single cells.'],
['Ancestors of animals (single cells to colonies)','Multicellular animals are thought to have come from single-celled organisms like choanoflagellates gathering together.'],
['Bilaterians (small worms)','A body with a front and back, top and belly. A rice-grain-sized animal crawling on the sea floor, too small to see on this screen.'],
['Early vertebrates','Jawless fish relatives a few cm long, like Haikouichthys. They have a notochord, the forerunner of the backbone.'],
['Jawless fish','Agnathans with bony plates guarding the head. Fish with jaws come next.'],
['Lobe-finned fish (fish with bones in their fins)','Relatives of coelacanths and lungfish. The bones in their fins later become arms and legs.'],
['Relatives of Tiktaalik','Arm-like bones in the fins and a neck that can move. They lived in shallow water at the edge.'],
['Early tetrapods','Four legs with toes. They still spent much of their time near water.'],
['Early synapsids','They laid shelled eggs and could live on dry land. Lizard-like, but on the mammal line.'],
['Cynodonts','Dog-like teeth and legs starting to tuck under the body. Close relatives of the direct ancestors of mammals.'],
['Early mammals','Mouse-sized animals. Active at night, they lived at the feet of dinosaurs.'],
['Small mammals','After the dinosaurs vanished, the small mammals that survived quickly became diverse.'],
['Early primates','They lived in trees, with forward-facing eyes and grasping hands.'],
['Early apes (Proconsul)','A tailless ape. Fossils have been found on the shore of Lake Victoria in Kenya.'],
['Early humans','Sahelanthropus and Ardipithecus. At the edge of forest and grassland, they began standing and walking on two legs.'],
['Australopithecus','1 to 1.5 m tall. The brain was about the size of a chimpanzee’s, but they walked on two legs.'],
['Early Homo (Homo habilis and others)','The brain grew larger, and they made and used stone tools.'],
['Homo erectus','A body close to modern humans, walking long distances. They began to use fire.'],
['Homo heidelbergensis','Often thought to be the common ancestor of Neanderthals and us (debated).'],
['Homo sapiens','Our species. They lived in small groups, hunting and gathering.'],
['Homo sapiens (herding and farming)','Keeping cattle, making fields and living in villages.'],
['Homo sapiens (today)','You, today.'],
];

// species names (life.js S()); a part in parentheses is dropped for labels
const SP_EN={strom:'Stromatolites',algae:'Algae',charnia:'Charnia',dickinsonia:'Dickinsonia',trilobite:'Trilobites',anomalo:'Anomalocaris',
 chordate:'Early vertebrates (Haikouichthys and others)',agnathan:'Jawless fish (armored fish)',nautiloid:'Orthocone (nautilus relative)',eurypterid:'Sea scorpions',
 placoderm:'Placoderms (Dunkleosteus and others)',shark:'Sharks',fish:'Fish',lobefin:'Lobe-finned fish (bones in their fins)',ammonite:'Ammonites',
 ichthyo:'Ichthyosaurs',plesio:'Plesiosaurs',mosasaur:'Mosasaurus',whale:'Early whales (Basilosaurus and others)',
 millipede:'Land arthropods (millipedes and others)',tiktaalik:'Tiktaalik',tetrapod:'Early tetrapods (Ichthyostega and others)',meganeura:'Meganeura (giant dragonfly)',
 amphib:'Amphibians (Eryops and others)',synapsid:'Early synapsids',dimetrodon:'Dimetrodon',gorgon:'Gorgonopsians',lystro:'Lystrosaurus',cynodont:'Cynodonts',
 smalltheropod:'Small theropods',sauropod:'Sauropods',bigtheropod:'Large theropods',stego:'Kentrosaurus (stegosaur)',ornithopod:'Ornithopods (Iguanodon and others)',
 pterosaur:'Pterosaurs',mammaliaform:'Early mammals',bird:'Birds',mammal:'Small mammals',gastornis:'Gastornis',primate:'Early primates',ape:'Proconsul (early ape)',
 elephant:'Elephant relatives',antelope:'Antelope',giraffe:'Giraffes',hippo:'Hippos',croc:'Crocodiles',lion:'Lion relatives',
 hom_early:'Early humans (Sahelanthropus, Ardipithecus)',australo:'Australopithecus',paranthropus:'Paranthropus',habilis:'Homo habilis',erectus:'Homo erectus',
 heidel:'Homo heidelbergensis',sapiens:'Homo sapiens',person:'People today',cattle:'Cattle (herding)',canoe:'Dugout canoe',plane:'Airplane',
 moss:'Mosses',cooksonia:'Cooksonia',fern:'Ferns',archaeopteris:'Archaeopteris',lepido:'Lepidodendron (scale tree)',treefern:'Tree ferns',conifer:'Conifers',
 cycad:'Cycads',broadleaf:'Broadleaf trees (flowering trees)',palm:'Palms',grass:'Grasses',acacia:'Acacia',
 hut:'Huts (village)',fire:'Campfire',building:'Buildings',car:'Cars',train:'Railway'};

if(LANG==='en'){
  GEO.forEach((g,i)=>{g[1]=GEO_EN[i]});
  KIND.earth[0]='Earth';KIND.life[0]='Life';KIND.extinct[0]='Extinction';KIND.human[0]='Humans';
  EVENTS.forEach((e,i)=>{e[2]=EVENTS_EN[i][0];e[3]=EVENTS_EN[i][1]});
  ANCESTORS.forEach((a,i)=>{a[1]=ANCESTORS_EN[i][0];a[2]=ANCESTORS_EN[i][1]});
}
